package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/Swif7ify/Obelisk-CLI/internal/engine"
	"github.com/Swif7ify/Obelisk-CLI/internal/scanner"
)

var flagExport string

var reportCmd = &cobra.Command{
	Use:   "report [path]",
	Short: "Generate and export a health report",
	Long:  "Runs a health check and exports the results as Markdown or JSON.",
	Args:  cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		projectPath := ""
		if len(args) > 0 {
			projectPath = args[0]
		}

		cfg := engine.Config{
			ProjectPath: projectPath,
			APIKey:      flagAPIKey,
			Model:       flagModel,
			Verbose:     flagVerbose,
		}

		fmt.Println("🏛️ Obelisk — Generating report...")
		result, err := engine.Run(cfg, func(phase string) {
			fmt.Printf("  → %s\n", phase)
		})
		if err != nil {
			return err
		}

		switch strings.ToLower(flagExport) {
		case "json":
			return exportJSON(result)
		case "markdown", "md":
			return exportMarkdown(result)
		default:
			return exportMarkdown(result)
		}
	},
}

func exportJSON(result *engine.Result) error {
	data, err := json.MarshalIndent(map[string]interface{}{
		"scan_result": result.ScanResult,
		"report":      result.Report,
		"detection":   result.Detection,
	}, "", "  ")
	if err != nil {
		return err
	}
	fmt.Println(string(data))
	return nil
}

func exportMarkdown(result *engine.Result) error {
	r := result.Report
	s := result.ScanResult

	fmt.Printf("# 🏛️ Obelisk Health Report\n\n")
	fmt.Printf("**Project:** %s\n", s.ProjectPath)
	fmt.Printf("**Type:** %s (%s)\n", result.Detection.Framework, result.Detection.Type)
	fmt.Printf("**Files:** %d | **Directories:** %d\n\n", s.FileCount, s.DirCount)
	
	if r != nil {
		fmt.Printf("## Grade: %s (%d/100)\n\n", r.Grade, r.OverallScore)
		fmt.Printf("| Category | Score |\n|---|---|\n")
		fmt.Printf("| Security | %d/100 |\n", r.SecurityScore)
		fmt.Printf("| Architecture | %d/100 |\n", r.ArchitectureScore)
		fmt.Printf("| Quality | %d/100 |\n\n", r.QualityScore)
		fmt.Printf("## Summary\n\n%s\n\n", r.Summary)
	}

	if len(s.Findings) > 0 {
		fmt.Printf("## Findings (%d total)\n\n", len(s.Findings))
		criticals := filterBySeverity(s.Findings, scanner.SeverityCritical)
		errors := filterBySeverity(s.Findings, scanner.SeverityError)
		warnings := filterBySeverity(s.Findings, scanner.SeverityWarning)

		if len(criticals) > 0 {
			fmt.Printf("### 🔴 Critical (%d)\n\n", len(criticals))
			for _, f := range criticals {
				fmt.Printf("- **%s** — %s", f.Title, f.Description)
				if f.File != "" {
					fmt.Printf(" (`%s`)", f.File)
				}
				fmt.Println()
			}
			fmt.Println()
		}
		if len(errors) > 0 {
			fmt.Printf("### 🟠 Errors (%d)\n\n", len(errors))
			for _, f := range errors {
				fmt.Printf("- **%s** — %s", f.Title, f.Description)
				if f.File != "" {
					fmt.Printf(" (`%s`)", f.File)
				}
				fmt.Println()
			}
			fmt.Println()
		}
		if len(warnings) > 0 {
			fmt.Printf("### 🟡 Warnings (%d)\n\n", len(warnings))
			for _, f := range warnings {
				fmt.Printf("- %s", f.Title)
				if f.File != "" {
					fmt.Printf(" (`%s`)", f.File)
				}
				fmt.Println()
			}
			fmt.Println()
		}
	}

	if r != nil && len(r.Recommendations) > 0 {
		fmt.Printf("## Recommendations\n\n")
		for i, rec := range r.Recommendations {
			fmt.Printf("%d. %s\n", i+1, rec)
		}
	}

	fmt.Printf("\n---\n*Generated by Obelisk CLI*\n")
	return nil
}

func filterBySeverity(findings []scanner.Finding, sev scanner.Severity) []scanner.Finding {
	var out []scanner.Finding
	for _, f := range findings {
		if f.Severity == sev {
			out = append(out, f)
		}
	}
	return out
}

func init() {
	reportCmd.Flags().StringVar(&flagExport, "export", "markdown", "Export format: markdown, json")
	rootCmd.AddCommand(reportCmd)

	// Suppress unused variable warning
	_ = os.Stdout
}
